### ISSUE TITLE
Support iceberg external table

### ISSUE THREAD

**Issue by caneGuy** [StarRocks/starrocks#1030]
## Enhancement
More and more users are using external table of starrocks, and some users use iceberg to build a lakehouse platform. We can support the iceberg table as an external table, and then we can use starrocks to analyze the iceberg table.
This is a parent issue for iceberg table. We will add TODOs to this issue.
TODOs:
- [x] Iceberg table design document  [Design doc](https://docs.google.com/document/d/1LtIX7v_i5PdazthzC6tpeGe_TR3Zza8LW2SPNUCJdmA/edit?usp=sharing)
- [x] Support iceberg on HDFS #2225 
- [x] Support iceberg on OSS
- [x] Support hive catalog for iceberg #2225 
- [ ] Support hadoop catalog for iceberg #3453 
- [x] Table statistics for planner CBO #2805 
- [ ] TimeTravel grammar support #3451 
- [x] Metadata cache #3497 
- [ ] Support Avro reader for iceberg
- [ ] Support iceberg v2 format #3452
- [x] Support scan column prune #2871 
- [x] Support predicate pushdown #2792 
- [x] Support join reorder #3496 
- [ ] Support custom catalog #3826 

cc @miomiocat @Ielihs

**Comment by caneGuy** [comment]
I wrote a draft for 'support query iceberg table', PTAL!

**Comment by tiannan-sr** [comment]
https://github.com/StarRocks/starrocks/issues/3469

**Comment by tiannan-sr** [comment]
#3469

**Comment by tiannan-sr** [comment]
#3469
