### ISSUE TITLE
[Enhancement] Subquery tramsformation refactor

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#10530]
## Background

Currently, the processing of subquery is as follows:
1. Parse `Expr` expression, transform `Subquery` to `ApplyOperator`, maintaining `Subquery -> ColumnRefOperator` mappings while processing.
2. Transform `Expr` expression to `ScalarOperator` expression, and replace `Subquery` with `ColumnRefOperator` using the mapping created in step1.

Here is the problem, in this step2, some scalar rewrite rule will be performed, such as `FoldConstantsRule`, some unnecessary subexpression like `2 < 3 or exists(select * from t2 where t0.v2 = t2.v2)` may be optimized out. So there is no chance to eliminate the unnecessary `ApplyOperator` from the logical plan.

For the below query, the subquery can be simply removed, because `2 < 3 or exists(select * from t2 where t0.v2 = t2.v2)` is always true.

```sql
select * from t0
where t0.v1 = 1 and ( 2 < 3 or exists(select * from t2 where t0.v2 = t2.v2));
```

The equivalent query is

```sql
select * from t0
where t0.v1 = 1;
```

## Roadmap

So we need to refactor the processing of the subquery transformation.

The main idea is to delay the subquery parse timing, the main stages are as follows:

1. Transform `Expr` to `ScalarOperator`.
2. Parse `Subquery` to `ApplyOperator` at a proper time.

And here is another problem, when transforming `Expr` to `ScalarOperator`, we cannot know the real output type of the `Subquery`, for some special expression like `case when` and `if/ifnull/nullif/coalesce`, the return type relying on the expr type which is also undertermined until subquery is parsed.

So I'm going to split this into three tasks:
- [x] Add a temporary pseudo type `SubqueryType` for `SubqueryOperator` and add rewriter rule `ReplaceSubqueryTypeRewriteRule` to recalculate the function singnature of `case when` and `if/ifnull/nullif/coalesce` after subquery is parsed.  #10516
- [x] Decope subquery parse process into to steps. For the first step, we transform `Subquery` to `SubqueryOperator` while saving the corresponding `applyOperator`. And for the next step, we can attach the saved `ApplyOperator` to the logical plan.  #11141 
- [ ] Push the second step to the optimize stage.
