### ISSUE TITLE
Support (array/json/percentile/hll_hash/bitmap_hash/null) for SparkLoad

### ISSUE THREAD

**Issue by xiaoyong-z** [StarRocks/starrocks#10588]
#### Related issue #10218

For a table like following:
```SQL
create table agg_tbl(
  col_tinyint tinyint
  ,col_date date
  ,col_char char(10)
  ,col_string string
  ,col_smallint smallint
  ,col_timestamp datetime
  ,col_varchar varchar(100)
  ,col_boolean boolean
  ,col_int int max
  ,col_bigint bigint max
  ,col_float float sum
  ,col_double double min
  ,col_decimal decimal(38,18) max
  ,col_largeint largeint max
  ,col_array array<string> replace
  ,col_json json replace
  ,col_bitmap bitmap BITMAP_UNION NULL
  ,col_hll HLL HLL_UNION
  ,col_percent percentile percentile_union
)
ENGINE=OLAP
aggregate KEY(col_tinyint,col_date,col_char,col_string,col_smallint,col_timestamp,col_varchar,col_boolean)
DISTRIBUTED BY HASH(col_tinyint) BUCKETS 3
PROPERTIES ("replication_num" = "3");
```
Spark Load
```SQL
LOAD LABEL compaction_spark_load_69fb3025 (
  DATA INFILE("xxx/fake_data0.csv)")
  INTO TABLE `agg_tbl` 
  (c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14)
  SET 
  (col_tinyint=c1,col_date=c2,col_char=c3,col_string=c4,col_smallint=c5,
  col_timestamp=c6,col_varchar=c7,col_boolean=c8,col_int=c9,col_bigint=c10,
  col_float=c11,col_double=c12,col_decimal=c13,col_largeint=c14,
  col_bitmap=bitmap_hash(c3),col_hll=hll_hash(c9),
  col_percent = percentile_hash(col_double)
  )
)
WITH RESOURCE test_spark_resource  
PROPERTIES("timeout"="300","max_filter_ratio"="0.5");
```
will fail. Error msg: App failed.

At the same time, broker load
```SQL
LOAD LABEL compaction_spark_load_69fb5 (
  DATA INFILE("xxx/fake_data0.csv")
  INTO TABLE `agg_tbl`
  (c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14)
  SET  
 (col_tinyint=c1,col_date=c2,col_char=c3,col_string=c4,col_smallint=c5,
    col_timestamp=c6,col_varchar=c7,col_boolean=c8,col_int=c9,col_bigint=c10,
    col_float=c11,col_double=c12,col_decimal=c13,col_largeint=c14
  )
) WITH BROKER hdfs_broker
PROPERTIES("timeout"="300","max_filter_ratio"="0.5");
```
can success
# Fail reason
Spark fail for the following reason:
1. not support array, json, percentile type
2. although support hll, bitmap, but it doesn't support hll_hash, bitmap_hash
3. if we don't set data for col_array and col_json, spark load can not auto fill null like broker load / routine load.

# Task split
- [ ] support array
- [ ] support json
- [ ] support percentile
- [ ] support hll_hash
- [ ] support bitmap_hash
- [ ] auto fill null if user don't provide data in load expr
