### ISSUE TITLE
[Feature] Support StructType in StarRocks.

### ISSUE THREAD

**Issue by Smith-Cruise** [StarRocks/starrocks#12339]
## Feature request

Support StructType in StarRocks.

## Roadmap

- [x] Implement StructType infra in BE.
- [x] Support read StructType data from ORC.
- [x] Support read StructType data from Parquet.
- [x] Support StructType in FE.
- [ ] Support lazyload.
