### ISSUE TITLE
StarRocks Roadmap 2022

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#1244]
## Core system
Q1 

- [x] Refactor memory management framework #703
- [x] Global dictionary for low-cardinality optimization #559
- [x] Pipeline execution engine  (check sig/pipeline)
- [x] CTE reuse #1318

Q2 

- [x] JSON type
- [x] Add more statistics for CBO
- [x] New parser in FE
- [x] Window function performance improvement
- [x] Map type #10677  

Q3

- [x] Result cache and segment cache #9194 
- [ ] Unified data ingestion interface #7170
- [x] Auto detecting bucket number
- [ ] Data encryption
- [x] Compaction Improvement
- [x] #1980

Q4 

- [ ] Z-order 
- [ ] Cross cluster replication
- [ ] Index for array type
- [ ] Row-oriented table

## Separation of compute and storage
Q1 

- [x] Overall architectural design.

Q2 

- [x] Separation of compute and storage is supported for duplicate tables with feature limits.

Q3 

- [x] Supports log storage.
- [ ] Support load balance. 
- [ ] Separation of compute and storage is supported for primary tables  #14853

Q4 

- [ ] Support Separation of compute and storage in local storage
- [ ] High availbility improvement

## Serverless
Q2 

- [x] Compute Node supported #5441
- [x] Execution unit can be routed to the compute cluster.

Q3 

- [ ] Global cache layer
- [x] K8s managed compute cluster https://github.com/StarRocks/starrocks-kubernetes-operator

Q4
- [ ] Support multi compute cluster 

## Materialized view
Q2

- [x] Support multi-table MV but only can be updated  asynchronously #3680 

Q3

- [x] Query rewrite for Multi-table MV #11386
- [ ] Support for single table incremental materialized view synchronously

Q4

- [ ] Support for multi table join incremental materialized view synchronously
- [x] External table materialized view

## Update
Q1 

- [x] Support schema change for primary key model. #1266 
- [x] Primary key model released

Q2

- [x] Partial update supported
- [x] Supported partial update with any column
- [x] Primary index persistence

Q3 

- [x] Support update and delete syntax. #438
- [x] Support Conditional update.

Q4 

- [ ] Support merge into syntax.

## Data lake analytics
Q1

- [x] Support hive external table on S3. #735 #1336
- [x] Support Iceberg external table.  #1030 

Q2

- [x] Hudi COW(copy-on-write)  external table. #2772 
- [x] JDBC external table.
- [x] New Connector framework phase 1#5062

Q3 

- [ ] New Connector framework phase 2 #7268
- [x] Hudi MOR(merge-on-read) external table.
- [x] Local cache

Q4

- [x] #10677
- [ ] Support delta lake #11972 
- [ ] Open StarLake table format

## Resource management

Q1 

- [x] Resource group preview #3440

Q2 

- [x] Large query fusion and fast positioning
- [x] Add external table into resource group

Q3 

- [x] Adding Ingestion into resource group
- [ ] Adding compaction into resource group

Q4 

- [x] priority queue for requests. 
 
## Batch processing
Q3 release 

## Stream Processing
Q4 release 

## Ecosystem
Q1 

- [x] Flink connector. https://github.com/StarRocks/starrocks-connector-for-apache-flink
- [x] Seatunnel connector https://github.com/apache/incubator-seatunnel/pull/3060

Q2 

- [x] UDF supported #2742 
- [x] DBT supported https://github.com/StarRocks/dbt-starrocks/
- [ ] Airbyte supported 

Q3

- [x] Support Pulsar  #7893
- [ ] Support Kinesis 
- [ ] Kettle connector #1355 

## Functions
- [x] Retention  #4065
- [x] WindowFunnel  #4985 #5290 
- [ ] Aggregation functions #1938 
- [ ] DateTime functions #6501 #6951 #5187 

## 4A (Authentication/ Authorization/ Account / Audit)
- [ ] Role base access control 
- [ ] Fine-grained privileges
- [ ] Password lifetime management
- [ ] Kerberos/Sentry/Ranger integration

## Ingestion & unloading
- [ ] Unified Ingestion syntax, use copy into instead of broker load / routine load / stream load
- [x] #16333
- [ ] Export to local file
- [ ] Add WAL for frequent insertion
- [x] Json load optimization: use simdjson instead of fast json, less type conversion #1780
- [ ] More csv ingestion format options: SKIP_HEADER  ESCAPE_UNENCLOSED_FIELD DATE_FORMAT ENCODING .. 

## Usability
- [x] #1193 
- [x] #1125 
- [x] #2742 

## Release plan & notes
- [x] #12064 
- [x] #10910
- [x] 2.3 Release notes: https://github.com/StarRocks/starrocks/releases/tag/2.3.0
- [x] #3035 
- [x] #4095

**Comment by vkingnew** [comment]
**Stream Processing**   when release this feature?

**Comment by vkingnew** [comment]
redpanda had support by materialize,have the plan to integrate?
https://github.com/redpanda-data/redpanda
https://materialize.com/docs/integrations/#redpanda
