### ISSUE TITLE
StarRocks Roadmap 2023

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#16445]
> Refer to roadmap [2022](https://github.com/StarRocks/starrocks/issues/1244)

# From OLAP to Lakehouse
## Data lake analytics
- [ ] Unified cache for data lake and StarRocks table
- [x] CBO optimization for no statistics.
- [ ] Incremental query and snapshot query from data lake
- [x] CTAS on data lake
- [ ] Indexes on data lake
- [x] Presto compatibility
- [ ] Kerberos integration with external catalogs
- [ ] More connectors(Kudu / Mongodb ... ) 
- Better table format support
    - [x] Better Hive/Iceberg/Hudi/Delta lake support
    - [ ] Hive/Iceberg/Hudi/Deltalake table sink  [Iceberg](https://docs.starrocks.io/en-us/latest/data_source/catalog/iceberg_catalog#sink-data-to-an-iceberg-table) 
    - [x] Parquet/Orc file writer
    - [ ] Open format: combine lake and local into one table
- More cloud integrations.
   - [x] Blob store integration 
   - [ ] Authentication and privileges. 
  
## Decoupled storage and computing
- StarOS
  - [ ] LogStore: for low latency application (including Primary key index, MV, FE metadata and row store)
  - [x] FileStore: High performance local storage  
  - [x] Resource manager: Support K8s and multi-cloud
  - [x] Multi blob storage support 
- StarRocks based on StarOS
  - [x] Fully function support for StarRocks (All data model, all DDL, DML and compaction service)
  - [x] Multi-warehouse and multi-cluster 
  - [ ] Decouple storage and computing for FE
  - [x] Cloud native architecture for primary key
  - [ ] Time travel query
  - [ ] Global cache and serverless cluster

# Core system

## Query
- [x] Operator spilling  [Docs](https://docs.starrocks.io/en-us/latest/administration/spill_to_disk)
- [ ] New computing scheduling framework
- [ ] Enhance Resource group ability for resource isolation
- [ ] Adaptive Query Processing
- [ ] Expression Codegen
- [ ] Low cardinality optimization for nested type
- [x] map/struct  native support, column reuse [Map Docs](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-types/Map) [Struct Docs](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-types/STRUCT)
- [x] Generated column (former called materialized column)  [Docs](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/generated_columns)
- [x] Query cache for join [Docs](https://docs.starrocks.io/en-us/latest/using_starrocks/query_cache)
- [x] Lambda for all data types [Docs](https://docs.starrocks.io/en-us/latest/sql-reference/sql-functions/Lambda_expression#lambda-expression)
- [ ] GEO type and functions

## Storage and data management

- [ ] Support larger scale of metadata, including decoupled storage and computing for FE,  Fine-grained lock for metadata, multi-tenant management.
- [ ] Unify metadata access through information schema.
- [x] Wise number of buckets detection and distributed column selection.
- [x] Auto partition creation and partition by expression.
- [ ] Unified table models. 
- [ ] Richer support for SQL: full support for update and merge into syntax
- [x] Better performance for partial update
- [ ] Z-order index
- [x] Row-oriented storage engine
- [ ] Full text / inverted index
- [ ] Index for json / map 
- [ ] Key-value api query, bypass SQL layer to shortcut. 

# Real-time
##  Ingestion
- [ ] Unified loading and unloading
- [x] Schema registry integration
- [ ] WAL support for high concurrency ingestion and millisecond level data freshness
- [ ] Support external stream
- [ ] Kinesis support
- [x] Pb/avro data format support #16662

## Materialized view
- [x] Query rewrite optimization [Docs](https://docs.starrocks.io/en-us/latest/using_starrocks/query_rewrite_with_materialized_views)
- [x] External table materialized view [Docs](https://docs.starrocks.io/en-us/latest/using_starrocks/data_lake_query_acceleration_with_materialized_views)
- [x] Spilling and resource group for materalized view 
- [ ] Streaming materialized view for single-table operator.
- [ ] Streaming materialized view for multi-table join.
- [ ] Streaming materialized view for deleting and updating.
- [ ] StarRocks internal stream and binlog.
- [ ] Materialized view for external stream.
- [ ] Incremental refresh for external table materialized view.

# Ecosystem

## BI connector
- [ ] Tableau connector / better compatibility
- [x] Metabase connector / better compatibility
- [x] Superset connector / better compatibility
- [x] Redash connector / better compatibility

## SQL editor / notebook
- [ ] DBeaver integration
- [ ] Datagrip integration
- [ ] Hex integration
- [ ] QueryBook integration

## ETL tools
- [x] Airbyte connector https://github.com/StarRocks/starrocks/tree/main/contrib/destination-starrocks
- [ ] Fivetran connector
- [x] Optimize the DBT connector

## Compute engine
- [x] Optimize flink connector
- [x] Optimize spark connector

## Monitor
- [x] Datadog integration https://github.com/StarRocks/starrocks/tree/main/contrib/datadog-connector

# Security
- [x] Fully support for RBAC. [Docs](https://docs.starrocks.io/en-us/latest/administration/privilege_overview)
- [x] Plugin framework.
- [x] Ranger integration. 

# Release 
- [x] https://github.com/StarRocks/starrocks/issues/18125
- [x] [3.1 release notes](https://github.com/StarRocks/starrocks/releases/tag/3.1.0)
- [x] https://github.com/StarRocks/starrocks/issues/33079

**Comment by vkingnew** [comment]
This issue should   stick on the  top  of all issue. Please help put it to the Begin.

**Comment by alberttwong** [comment]
@Dshadowzh Can we update this?

**Comment by Leowuqunqun** [comment]
@Dshadowzh  MongoDB connect Is anyone following up? If not, I'd love to try

**Comment by wangsimo0** [comment]
> @Dshadowzh MongoDB connect Is anyone following up? If not, I'd love to try

not yet, of course, more than welcome

**Comment by LonwoLonwo** [comment]
https://github.com/dbeaver/dbeaver/issues/21583 ;)

**Comment by kk25114** [comment]
airbyte 新版本0.63.13版本不支持貌似,能更新下docker连接器吗

**Comment by kk25114** [comment]
> airbyte 新版本0.63.13版本不支持貌似,能更新下docker连接器吗

"io.airbyte.integrations.destination.starrocks.exception.StreamLoadFailException: Stream load failed because of unknown exception, db: airbyte, table: _airbyte_tmp_bgb_example, label: airbyte__airbyte_tmp_bgb_example_e52eaaf1-861d-4b2b-9fca-bb2e795994821723452021594\n\tat io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:166)\n\tat io.airbyte.integrations.destination.starrocks.StarRocksBufferedConsumerFactory.lambda$recordWriterFunction$2(StarRocksBufferedConsumerFactory.java:100)\n\tat io.airbyte.integrations.destination.record_buffer.InMemoryRecordBufferingStrategy.flushAllBuffers(InMemoryRecordBufferingStrategy.java:87)\n\tat io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:291)\n\tat io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82)\n\tat io.airbyte.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:95)\n\tat io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:186)\n\tat io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:123)\n\tat io.airbyte.integrations.destination.starrocks.StarRocksDestination.main(StarRocksDestination.java:51)\nCaused by: java.lang.NullPointerException: Cannot invoke \"io.airbyte.integrations.destination.starrocks.StreamLoadResponse$StreamLoadResponseBody.getStatus()\" because \"streamLoadBody\" is null\n\tat io.airbyte.integrations.destination.starrocks.DefaultStreamLoader.send(DefaultStreamLoader.java:132)\n\t... 8 more\n",
  "timestamp" : 1723452022291
}, {
  "failureOrigin" : "destination",
  "internalMessage" : "Destination process exited with non-zero exit code 1",
  "externalMessage" : "Something went wrong within the destination connector",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 220,
    "connector_command" : "write"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.DestinationException: Destination process exited with non-zero exit code 1\n\tat io.airbyte.workers.general.BufferedReplicationWorker.readFromDestination(BufferedReplicationWorker.java:493)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:235)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\n",
  "timestamp" : 1723452022421
}, {
  "failureOrigin" : "replication",
  "internalMessage" : "io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.",
  "externalMessage" : "Something went wrong during replication",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 220
  },
  "stacktrace" : "java.lang.RuntimeException: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:538)\n\tat io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsyncWithTimeout$5(BufferedReplicationWorker.java:263)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:178)\n\tat io.airbyte.workers.general.BufferedReplicationWorker$CloseableWithTimeout.lambda$close$0(BufferedReplicationWorker.java:536)\n\t... 5 more\n",
  "timestamp" : 1723452022422
} ]
2024-08-12 08:40:22 platform > 
2024-08-12 08:40:22 platform > ----- END REPLICATION -----
2024-08-12 08:40:22 platform > 
2024-08-12 08:40:22 platform > Retry State: RetryManager(completeFailureBackoffPolicy=BackoffPolicy(minInterval=PT10S, maxInterval=PT30M, base=3), partialFailureBackoffPolicy=null, successiveCompleteFailureLimit=5, totalCompleteFailureLimit=10, successivePartialFailureLimit=1000, totalPartialFailureLimit=20, successiveCompleteFailures=1, totalCompleteFailures=1, successivePartialFailures=0, totalPartialFailures=0)
 Backoff before next attempt: 10 seconds
