### ISSUE TITLE
Improve array function roadmap

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#17669]
## Feature

* All array function support decimalV3
   - [x] array_slice/array_distinct/array_sort/reverse/array_intersect/array_concat
   - [x] array_max/array_min/array_sum/array_avg
   - [x] arrays_overlap/array_difference
   - [x] array_sortby/array_contains_all/array_contains_any
   - [x] array_append/array_remove/array_position/array_contains
   - [x] array_agg
   - [x] array_length

* array function support nested type(Array/Map/Struct)
   - [x] array_slice/array_concat
   - [x] array_length/array_append/array_remove/array_position
   - [x] array_contains/array_contains_all/array_contains_any
   - [x] array_agg
   - [x] array_sortby
   - [x] reverse/array_distinct/array_intersect/arrays_overlap

## Enhancement
* array_slice 
  * check negative offset
  * support a constant offset & length template implemention

* array_distinct
  * support JSON type

## Performance
- [ ] array_agg/array_append/array_filter/array_position @fzhedu 
- [ ] array_concat/array_contains/unnest/array_slice @Seaven  
- [ ] cast array to other type @Seaven 
- [ ] array_avg/array_max/array_min/array_sum/array_contains_all/array_cum_sum
- [ ] array_difference/array_distinct/array_intersect/array_join/array_length/array_map
- [ ] array_remove/array_sort/array_sortby/arrays_overlap/array_to_bitmap/reverse

## Other
- [ ] any_value support nested-type @LiShuMing
