### ISSUE TITLE
Struct/Map support roadmap

### ISSUE THREAD

**Issue by Seaven** [StarRocks/starrocks#19355]
## Backgroud
At present, starrocks already supports static Struct/Map types in the external table, and can query external tables (hive/parquet/....) through related expressions. Some user will load the external data into starrocks, but starrocks has not supported the storage and import process of Struct/Map in the OLAP table.

## Target
1. Internal tables support DDL operations on static Struct/Map type columns
2. Support importing Struct/Map types from external data sources to starrocks
3. Support querying Struct/Map and related expressions
4. Optimize Struct/Map query performance as much as appearance

## Currently supported
1. Struct/Map storage of internal tables (the code is ready, but needs to be test & review)
2. Memory column structure of Struct/Map
3. Some simple expressions

## Phase 1.
1. Internal tables support DDL operations on static Struct/Map type columns
  - [ ] Table structure creation

2. Support importing Struct/Map types from external data sources to starrocks
  
  - [ ] Data source format (Parquet, ORC)
  - [ ] Import method (Insert Into, Broker Load)

3. Query Struct/Map query performance optimization

  - [ ] Struct/Map column access performance optimization
  - [ ] Structure internal column cutting design & optimization

**Comment by mcgray** [comment]
We would very much like struct support for views on top of Iceberg tables.

**Comment by pedrong** [comment]
Also looking forward for these along with Views support

**Comment by Seaven** [comment]
> We would very much like struct support for views on top of Iceberg tables.

look at the requirement, @zombee0

**Comment by Seaven** [comment]
> Also looking forward for these along with Views support

View support now

**Comment by mabbasi90** [comment]
Hey guys,
When we can expect supporting struct/map types in stream load? Is there an estimate for that?

**Comment by ever4Kenny** [comment]
Hi guys, any update on the "Support load Struct/Map types: Data source format (CSV)"?

**Comment by ever4Kenny** [comment]
Any tips if I would love to work on  "Support load Struct/Map types: Data source format (CSV)"? Could you guys shed some light on the entry class？

**Comment by jaogoy** [comment]
@ever4Kenny Currently, we want to support loading Struct data thourgh JSON format first. (Its' similar for CSV)
The rough idea is that:
1. Users convert Struct data into a string (structed-formatted string, or json-formatted string), or a JSON object.
2. The corresponding target column is defined as a Struct data type column.
3. Stream Load or Routine Load can convert such a string or JSON object into the target Struct data column.
