### ISSUE TITLE
[Enhancement] Parallel merge processing

### ISSUE THREAD

**Issue by liuyehcf** [StarRocks/starrocks#20534]
## Background

Currently, the full sort process can be illustrated as the below graph. Mainly, it has three steps, which are:
1. `Local Sort`: This step can be performed across all nodes and using each node's available cores.  It is highly paralleled right now.
2. `Local Cascade Merge`: Each node will have a local merge step to gather all the upcoming sorted streams into one. And it only uses one thread.
3. `Global K-Merge`: One node will be chosed to do the global merge at plan stage, and all other nodes(including itself) will send its sorted streams to this selected node. And it only uses one thread.

``` ┌──────────────────────────────────────────────────────────────────────┐
 │                                                                      │
 │       ┌──────────────┐                                               │
 │       │  Local Sort  ├─────────────┐                                 │
 │       └──────────────┘             │                                 │
 │                                    │                                 │
 │       ┌──────────────┐             │                                 │
 │       │  Local Sort  ├──────────┐  │                                 │
 │       └──────────────┘          │  │     ┌───────────────────────┐   ├────────────────────────────────┐
 │                                 ├──┼────►│  Local Cascade Merge  │   │                                │
 │       ┌──────────────┐          │  │     └───────────────────────┘   │                                │
 │       │  Local Sort  ├──────────┘  │                                 │                                │
 │       └──────────────┘             │                                 │                                │
 │                                    │                                 │                                │
 │       ┌──────────────┐             │                                 │                                │
 │       │  Local Sort  ├─────────────┘                                 │                                │
 │       └──────────────┘                                               │                                │
 │                                                                      │                                │
 └──────────────────────────────────────────────────────────────────────┘                                │
                                                                                                         │
 ┌──────────────────────────────────────────────────────────────────────┐                                │
 │                                                                      │                                │
 │       ┌──────────────┐                                               │                                │
 │       │  Local Sort  ├─────────────┐                                 │                                │
 │       └──────────────┘             │                                 │                                │
 │                                    │                                 │                                │
 │       ┌──────────────┐             │                                 │                                │
 │       │  Local Sort  ├──────────┐  │                                 │                                │                        ┌───────────────────┐
 │       └──────────────┘          │  │     ┌───────────────────────┐   │                                │                        │                   │
 │                                 ├──┼────►│  Local Cascade Merge  │   ├────────────────────────────────┼───────────────────────►│   Global K-Merge  │
 │       ┌──────────────┐          │  │     └───────────────────────┘   │                                │                        │                   │
 │       │  Local Sort  ├──────────┘  │                                 │                                │                        └───────────────────┘
 │       └──────────────┘             │                                 │                                │
 │                                    │                                 │                                │
 │       ┌──────────────┐             │                                 │                                │
 │       │  Local Sort  ├─────────────┘                                 │                                │
 │       └──────────────┘                                               │                                │
 │                                                                      │                                │
 └──────────────────────────────────────────────────────────────────────┘                                │
                                                                                                         │
 ┌──────────────────────────────────────────────────────────────────────┐                                │
 │                                                                      │                                │
 │       ┌──────────────┐                                               │                                │
 │       │  Local Sort  ├─────────────┐                                 │                                │
 │       └──────────────┘             │                                 │                                │
 │                                    │                                 │                                │
 │       ┌──────────────┐             │                                 │                                │
 │       │  Local Sort  ├──────────┐  │                                 │                                │
 │       └──────────────┘          │  │     ┌───────────────────────┐   │                                │
 │                                 ├──┼────►│  Local Cascade Merge  │   ├────────────────────────────────┘
 │       ┌──────────────┐          │  │     └───────────────────────┘   │
 │       │  Local Sort  ├──────────┘  │                                 │
 │       └──────────────┘             │                                 │
 │                                    │                                 │
 │       ┌──────────────┐             │                                 │
 │       │  Local Sort  ├─────────────┘                                 │
 │       └──────────────┘                                               │
 │                                                                      │
 └──────────────────────────────────────────────────────────────────────┘
```

Obviously， `Local Cascade Merge` and `Global K-Merge` can be further parallelized.

## Enhancement

Enlightened by [Merge Path - A Visually Intuitive Approach to Parallel Merging](https://arxiv.org/abs/1406.2628). A noval approach called `Merge Path` can help accelerate the merge process by using as many cores as possible. Details are omitted here, since the algorhtim is quite clearly described in the paper. 

## Tasks

- [ ] Implement the merge sort algorithm. And based on this algorithm, implement the merge component to fit into the pipeline workloads.
- [ ] Support Lazy materiazlied to lower the overhead. (Enlighted by [[Refactor] Lazy materialization of cascading merging](https://github.com/StarRocks/starrocks/pull/17998))
- [ ] Enable parallel merge by default.
- [ ] Delete switch session variable `enable_parallel_merge` and related stale codes.
