### ISSUE TITLE
Refactor Coordinator scheduler

### ISSUE THREAD

**Issue by ZiheLiu** [StarRocks/starrocks#27846]
- [x] Extract `JobInformation`. #27847
- [x] Remove delivery in batch.  #28005
- [x] Extract DAG
    - [x] Extract `ExecutionFragmentInstance`. #28056
    - [x] Extract `ExecutionFragment`, `FragmentInstance`. #28208
    - [x] Extract `ExecutionDAG`. #28208
- [x] Extract assignment workers to fragment instances. #29419
- [ ] Extract `ExecutionProfile`. #29488
- [x] Extract `Deploy`. #28208
- [ ] Use state machine pattern in Coordinator.
- [x] Add `show scheduler <SQL>` to show the distribution information of each fragment instance. #29387
