### ISSUE TITLE
Refactor DLA complex subfield pruned code

### ISSUE THREAD

**Issue by Smith-Cruise** [StarRocks/starrocks#33154]
We need to unify complex subfield pruned logic
- [ ] Reuse OLAP's column access path logic in DLA #33372
- [ ]  Refactor parquet get_next() code, using const column instead #33372
- [ ] Support map_values() function #33372
- [ ] Support unested() function
