### ISSUE TITLE
StarRocks Roadmap 2024

### ISSUE THREAD

**Issue by Dshadowzh** [StarRocks/starrocks#39686]
> Refer to roadmap  [2023](https://github.com/StarRocks/starrocks/issues/16445) [2022](https://github.com/StarRocks/starrocks/issues/1244)

# Shared-data & StarOS

- Align with all functionalities to shared-nothing
    - [ ] Sync materialized view
    - [ ] Generated column
    - [ ] Partial update with column mode
    - [ ] Optimize table and manual compaction
- Better cache system 
    - [ ] Multi-layer cache
    - [ ] Global cache
    - [ ] Cache Auto warmup
    - [ ] Cache black/whitelist
    - [ ] Refine evict algorithm
- StarOS internal optimization
    - [ ] Multi-replicas for shard management
    - [ ] Shard schedule optimization for large scale (more than 10M shards)
    - [ ] Local storage for staros
- [ ] Open API for StarRocks table format  (sink and source)
- [ ] Time Travel
- [ ] Backup support 
   
# Performance 
- [ ] Full columnar Json index 
- [ ] Cost model with primary key and foreign key constrains
- [ ] Arm optimization for codecs
- [ ] Adaptive DOP and adaptive query engine
- [ ] Global dictionary encoding
- [ ] Better IO schedule framework
- [ ] JIT / Codegen

# Easy to use
- [ ] List partition optimization
- Improve `files` table function 
    - [ ] Improve schema inference
    - [ ] CSV and json format support
    - [ ] Other format: Avro, Arrow, Protobuf
    - [ ] Better performance for read, predicates pushdown
- Insert statement improvement (on duplicate key, insert properties)
- Unified data ingestion with Pipe
    - [ ] Pipe for continuous ingestion from Kafka
    - [ ] Read from external stream table(Kafka) 
    - [ ] Continues data ingestion from SQS with Pipe
- [ ] Out-of-the-box parameters

# Data lake analytics
- Better lake format support

Lake | Read | Insert | DDL | Update/Delete/Merge into | Time travel | MV
--- | --- | --- | --- | --- | --- | ---
Hive | 2.0 - 2.3 | 3.2 |   |   | / | 2.5 - 3.1
Iceberg | 2.1 - 2.3 | 3.1 | 3.3 | 3.3 |   | 3.0 - 3.1
Hudi | 2.2 |   |   |   |   | 3.0
Paimon | 3.0 |   |   |   |   | 3.2
Delta lake | 3.0 |   |   |   |   | 3.2

- Materialized view improvement 
  - [ ] Improve partition mapping (list partition, expression partition)
  - [ ] Task scheduler & Linages
  - [ ] Better query rewrite 
- [ ] Text File format support
- [ ] Presto/Trino/Spark/Hive SQL compatibility 
- [ ] Presto/Trino/Spark/Hive UDF compatibility
- [ ] Automatic cooldown to lake format

# Data warehousing(batch and streaming)
## Batch processing & ETL improvement 
- [ ] Enable spilling by default globally
- [ ] Multi-statement transaction
- [ ] Temporary table
- [ ] Group execution
- [ ] Task auto retry
## Streaming processing & real-time update
- [ ] Schemaless partial update
- [ ] Merge into statement
- [ ] Binlog to flink and spark streaming
- [ ] Transaction level incremental refresh in materialized view (Aggregation, Join, functions)
- [ ] Incremental refresh for iceberg/Hudi/Paimon materialized view

# Metadata 
- [ ] Fine granularity Fe lock(from db level to table level)
- [ ] Decoupled storage for FE (kv store)
- [ ] Lake metadata optimization for Iceberg 

# All-in-one scenarios
- [ ] Search engine: Optimize full text inverted index
- [ ] KV store: Optimize row store for high concurrent point lookup
- [ ] Time series db: Asof join,  high concurrent ingestion
- [ ] Vector database:  vector index

# Release 
- 3.3 release plan

**Comment by arsenalzp** [comment]
Hello,
Any chance to have good-first-issue feature among those tasks?

**Comment by Dshadowzh** [comment]
> Hello, Any chance to have good-first-issue feature among those tasks?

Welcome, you can check this https://github.com/StarRocks/starrocks/issues/13300, we'll update more good-first-issues in 2024.

**Comment by Zhangg7723** [comment]
How about incremental refresh materialized view for external table like Iceberg or Hudi? I think this feature can reduce the cost of refresh mv

**Comment by Dshadowzh** [comment]
> How about incremental refresh materialized view for external table like Iceberg or Hudi? I think this feature can reduce the cost of refresh mv

Yes. We are considering about it, there is a `Incremental refresh for iceberg/Hudi/Paimon materialized view`. By the way, Iceberg and Hudi, which do you perfer?

**Comment by MatthewW00** [comment]
On yesterday 2024 roadmap meeting，mention that will support tag on BE in shared nothing mode，it like multi warehouse mechanism like in shared data mode，could split into load data warehouse\adhoc query warehouse\ETL warehouse...? And when will release?

**Comment by Dshadowzh** [comment]
> On yesterday 2024 roadmap meeting，mention that will support tag on BE in shared nothing mode，it like multi warehouse mechanism like in shared data mode，could split into load data warehouse\adhoc query warehouse\ETL warehouse...? And when will release?

https://github.com/StarRocks/starrocks/pull/38833 It has finished already, will be published in the next version.

**Comment by trikker** [comment]
Thanks, below is my wanted features and improvements:

1. Datalake Query
(1) support more types of catalogs, like oracle, tidb, oceanbase and greenplum(don't know if it is fully compatible with postgresql)
(2) support catalog metadata cache for JDBC MySQL, JDBC postgresql and the above catalogs
(3) support automatic sample and histogram statistic collection for Hive, Iceberg

2. Materialized View
(1) support rewrite for SQLs with UNION, ORDER BY and LIMIT
(2) support rewrite for nested-aggregation SQLs, aggregation-then-join SQLs and related-subquery SQLs with one MV
(3) enable view based mv rewrite to rewrite a query without needing user to query the view
(4) support incremental refresh of MV(like flink stream computing), rather than refresh a whole table or partition
(5) support materiailized view recommendation

3. Query Plan
(1) support query plan cache and plan binding for SQLs, like Oracle

4. Resource Management
(1) support CPU real hard limit for resource group, currently it is actually a soft limit;
(2) suport multi-warehouse for users or resource group, different users can only see only different part of the machines when executing queries

5. Stability
(1) memory spill still don't work for some SQLs when enable_spill is true and spill_mode is force, see issue: https://github.com/StarRocks/starrocks/issues/40936

**Comment by chengyi3192** [comment]
Expected to support deletion queries in the Parquet format of Iceberg

**Comment by Dshadowzh** [comment]
> Expected to support deletion queries in the Parquet format of Iceberg

We plan implementing it in v3.3

**Comment by Dshadowzh** [comment]
> Thanks, the following are our wanted features and improvements based on my tests on StarRocks and my company's business scenarios:

Thanks a lot for so much feedback. 
1. We want to improve JDBC catalog for more databases. It's a community driven project, It's welcome if you want to participate and we'll list some detail about this project later.
2. New statistics collection for hive and iceberg is WIP 
3. view-based mv rewrite is already finished.  You can create some independent issue for UNION, ORDER BY, LIMIT and nested-aggregation SQLs rewrite. We have some work around for these cases, if you have some specific scenarios, we'd like to prioritize these issues.
4. Query Plan is a good idea, if you have some basic design, we'd like to discuss details about that.
5. Hard limit for resource group and multi-warehouse are in our roadmap.

**Comment by trikker** [comment]
> > Thanks, the following are our wanted features and improvements based on my tests on StarRocks and my company's business scenarios:
> 
> Thanks a lot for the extensive feedback:
> 
> 1. We want to improve JDBC catalog for more databases. It's a community driven project, It's welcome if you want to participate and we'll list some detail about this project later.
> 2. New statistics collection framework for hive and iceberg is WIP
> 3. View-based mv rewrite is already finished(v3.3).You can create some independent issue for UNION, ORDER BY, LIMIT and nested-aggregation SQLs rewrite. We have some work arounds for these cases, if you have some specific scenarios, we'd like to prioritize these issues.
> 4. Query plan cache is a good idea, if you have some basic design, we'd like to discuss in details.
> 5. Hard limit for resource group and multi-warehouse are in our roadmap.

OK, hope we have a detailed communication later. Happy Spring Festival! ^_^

**Comment by inviscid** [comment]
Top priorities for our ability to migrate to StarRocks from Greenplum.  These two issues:

- Special Character Handling: https://github.com/StarRocks/starrocks/issues/38854
- Case Sensitive Column Names: https://github.com/StarRocks/starrocks/issues/40292

Plus, Time Travel natively in StarRocks without using an external Data Lake.

The 2024 Roadmap looks great.  Hoping we can get migrated so we can contribute to the journey.

**Comment by ericsun2** [comment]
This roadmap is exciting.

Let's collaborate on supporting Databricks Unity Catalog as well. Thanks a million.

**Comment by motto1314** [comment]
Connector: Directly reading data files instead of reading from BE.

Do you have a more detailed plan or issue for this feature?

thanks.

**Comment by chulucninh09** [comment]
Any thought about supporting Arrow flight SQL protocol for better data transportation? As data engineer & data scientist, we expect less overhead of converting from SQL (currently Mysql) protocol to pandas/pyarrow table

**Comment by giovannibonetti** [comment]
> 3\. View-based mv rewrite is already finished(v3.3).You can create some independent issue for UNION, ORDER BY...

I have just a question about this part, I think the documentation is confusing in this regard.

On one hand, [the limitations section of the Query rewrite with materialized views page says](https://docs.starrocks.io/docs/using_starrocks/query_rewrite_with_materialized_views/#limitations):

> **Limitations**
> In terms of materialized view-based query rewrite, StarRocks currently has the following limitations:
> ...
> - Materialized views defined with statements containing LIMIT, **ORDER BY**... cannot be used for query rewrite.
> ...

On the other hand, [the Set extra sort keys section of the Synchronous materialized view page says](https://docs.starrocks.io/docs/using_starrocks/Materialized_view-single_table/#set-extra-sort-keys):
> Suppose that the base table tableA contains columns k1, k2 and k3, where only k1 and k2 are sort keys. If the query including the sub-query where k3=x must be accelerated, you can create a synchronous materialized view with k3 as the first column.
> ```sql
> CREATE MATERIALIZED VIEW k3_as_key AS
> SELECT k3, k2, k1
> FROM tableA
> ```

If I understood it correctly, `ORDER BY k3, k2, k1` is implicit in the materialized view definition. So, it seems like ORDER BY is already working for materialized view query rewriting, isn't it?

**Comment by giovannibonetti** [comment]
Thanks for the explanation, @Dshadowzh. I have just a question about this part:

> 3\. View-based mv rewrite is already finished(v3.3).You can create some independent issue for UNION, ORDER BY...

I think the documentation is confusing in this regard.

On one hand, [the limitations section of the Query rewrite with materialized views page says](https://docs.starrocks.io/docs/using_starrocks/query_rewrite_with_materialized_views/#limitations):

> **Limitations**
> In terms of materialized view-based query rewrite, StarRocks currently has the following limitations:
> ...
> - Materialized views defined with statements containing LIMIT, **ORDER BY**... cannot be used for query rewrite.
> ...

On the other hand, [the Set extra sort keys section of the Synchronous materialized view page says](https://docs.starrocks.io/docs/using_starrocks/Materialized_view-single_table/#set-extra-sort-keys):
> Suppose that the base table tableA contains columns k1, k2 and k3, where only k1 and k2 are sort keys. If the query including the sub-query where k3=x must be accelerated, you can create a synchronous materialized view with k3 as the first column.
> ```sql
> CREATE MATERIALIZED VIEW k3_as_key AS
> SELECT k3, k2, k1
> FROM tableA
> ```

If I understood it correctly, `ORDER BY k3, k2, k1` is implicit in the materialized view definition. So, it seems like ORDER BY is already working for materialized view query rewriting, isn't it?

**Comment by malthe** [comment]
@chulucninh09 there's an open issue tracking [support for Apache Arrow Flight SQL](https://github.com/StarRocks/starrocks/issues/22944), but it would be great to get it on the 2024 roadmap.

Interestingly, Apache Doris has this [supported since 2.1](https://doris.apache.org/blog/arrow-flight-sql-in-apache-doris-for-10x-faster-data-transfer/), released on March 8th 2024.

**Comment by Dshadowzh** [comment]
> @chulucninh09 there's an open issue tracking [support for Apache Arrow Flight SQL](https://github.com/StarRocks/starrocks/issues/22944), but it would be great to get it on the 2024 roadmap.
> 
> Interestingly, Apache Doris has this [supported since 2.1](https://doris.apache.org/blog/arrow-flight-sql-in-apache-doris-for-10x-faster-data-transfer/), released on March 8th 2024.

We'll add this to the roadmap and launch the project soon. Thank you for your attention.

**Comment by sharfy** [comment]
请问一下 3.4版本大概什么时候可以发布

**Comment by gaigaikuaipao** [comment]
Is this year not the time for the functional development plan of a high-speed data transmission link based on Arrow Flight SQL。

**Comment by Dshadowzh** [comment]
@gaigaikuaipao Yes, we want to release it in 3.4. You can follow this PR https://github.com/StarRocks/starrocks/pull/50199

**Comment by jhcnet2** [comment]
I strongly hope for a multi-warehouse feature next year, similar to the compute node group in Apache Doris. I believe this is a very important feature for the Online+Batch service model

**Comment by colagy** [comment]
When will StarRocks support DDL,DML operations like UPDATE, DELETE, MERGE INTO, TRUNCATE PARTITION, ALTER TABLE with Iceberg is currently unknown.
