### ISSUE TITLE
PRs need to be checked to be merged into V3.2

### ISSUE THREAD

**Issue by jaogoy** [StarRocks/starrocks#41063]
- [ ] 9cbe0c29f4 [Enhancement] [cherry-pick] Make maximal varchar string length configurable in fe.conf and be.conf. (backport #38957) (#41008)
- [ ] a1944016ec [Enhancement] [Cherrypick] Support wild cards in the file paths for external tables (backport #40286)  (#40844)
- [ ] 9ed79f1e29 [cherrypick][branch-3.1-cs][Feature][Issue 39849]add datadog java/cpp profiling lib (#40652) (#40845)
- [ ] b90f0e2561 [Feature][Issue 39849] update BE/FE start shell to support Datadog profile (backport #39913) (#40154)
- [ ] dbe1a3b138 [Tool] Filter cases in fe ut script (backport #38889) (backport #38896) (#39033)
- [ ] 741d0442b7 [BugFix] fix blocked scan and add more logs to check blocked drivers (#34614)
- [ ] 5c0be965ad [BugFix] Fix SenderQueue may leak closure (#34940)
- [ ] ccc38edee5 [BugFix] fix lambda expr crash, backport (#33874)
- [ ] 27052b0cf2 [BugFix] clear state when lambda expr close (#33865)
- [ ] c85dd5f29a [Enhancement] refine log for abnormal queries (#33837)
- [ ] 9ddd5b277d [Feature] support dump slow driver stats (#33806)
- [ ] cf8f3644e8 [BugFix] Append null to nullable numeric column (#32767)
- [ ] f31aa1e6e0 [BugFix] Distinguish materialized view refreshed partitions are empty or cannot be rewritten (#32513)
- [ ] 5895e48333 [Enhancement] Support expression conversion of struct sub-column in Iceberg  (#32598)
- [ ] 7c1f6ab364 fix const
- [ ] 75902b00fa [backport][branch-3.1][BugFix] Fix analyze mv privilege check (#32032)
- [ ] f00db23823 [BugFix] Set Group Statistics with MaterializedView (#30530)
- [ ] a18bad998c [Enhancement] Resolve hostname in FE (#32056)
- [ ] b55373ad7e [BugFix] in cgroupv2 k8s env,  memory.max is in /sys/fs/cgroup/kubepods (#31406)
- [ ] 81766fd5c9 [BugFix] Fix transaction stream load LOAD_FINISHED metrics (#30063)
- [ ] 0c986b37af [Enhancement] Add session variables enable_table_prune_on_update (backport #31151) (#31211)

**Comment by LiShuMing** [comment]
https://github.com/StarRocks/starrocks/pull/32513 fixed by :https://github.com/StarRocks/starrocks/pull/34750/commits

**Comment by kevincai** [comment]
#40652 branch-3.2: https://github.com/StarRocks/starrocks/pull/40809

**Comment by meegoo** [comment]
#30063 https://github.com/StarRocks/starrocks/pull/41099

**Comment by kevincai** [comment]
#39913 branch-3.2: https://github.com/StarRocks/starrocks/pull/41108

**Comment by kevincai** [comment]
#31406: branch-3.2: https://github.com/StarRocks/starrocks/pull/41143
