### ISSUE TITLE
Pushing down OR predicates

### ISSUE THREAD

**Issue by ZiheLiu** [StarRocks/starrocks#43801]
## Feature request

Pushing down OR predicates:
- [x] Replace `vector<ColumnPredicate>` with PredicateTree. #43866
- [x] Parse OR predicates and add them to the PredicateTree. #44588
- [x] Rewrite predicates for ZoneMap. #43888 #44312
- [x] Apply ZoneMap Index. #45090
- [x] Apply Bloom Filter Index. #45459 
- [x] Apply Bitmap Index. #45603
- [x] Rewrite predicates for Dict Column. #43888 #44312
- [x] Apply predicate filtering. #44588
