### ISSUE TITLE
Support Large BinaryColumn

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#4618]
## Enhancement

In some scenarios: such as Array function, Join right table, Sort table, super long string > 1M, network packet, string function, etc., there will be a situation where the column length is greater than 4G, but the current Offset is uint32_t and cannot be represented> 4G bytes.

**current solution**

- [x] step1: Add BinaryColumnBase for support different size of offset #4619 
- [x] step2: Add LargeBinaryColumn #4713 
- [x] step3: Add interface upgrade_if_overflow for IColumn #4724 
- [ ] step4: Add inteface downgrade and has_large_column for IColumn
- [x] step5: HashJoin build key column after fetch each chunk for right table #4863 
- [ ] step6: HashJoin downgrade the output chunk before output
- [ ] step7: Other node support LargeBinaryColumn
- [ ] step8: Expr framework support LargeBinaryColumn
- [ ] step9: Shuffle framework support LargeBinaryColumn
