### ISSUE TITLE
Introducing a new framework for StarRocks to connects to external data source more easily

### ISSUE THREAD

**Issue by caneGuy** [StarRocks/starrocks#5062]
In StarRocks we have implemented 
1. a full vectorization engine
2. a new CBO optimizer
3. new pipeline based scheduling execution engine

We think these features will also greatly improve analytic queries on external storage systems. Now we have support hive/iceberg/hudi/jdbc, and we have users who want to query data stored on kudu. 
However, when we want to support new storage system, we need to do something like below:
- add new scannode/scan operator
- add create external table semantic for metadata synchronization
- add new prune rules 
- add new scan implementation rules
- other many changes on fe and be

It's really a tough job for most developers, and create external table for new storage system which is also unfriendly experience for users.
We will introduce a new framework for these reasons. The new framework will named as Connector APIs, and all related work will be tracked using this issue.
![image](https://user-images.githubusercontent.com/26762018/164753282-5016ed0f-45b8-49af-91ea-4ce1da246ab6.png)

**Phase 0:**
- [x] Comprehensive design documentation [DLA New FrameWork](https://docs.google.com/document/d/1dWx18ssITnfcmWsz3Iu3p6WhQq-POjADHhL50yz_3gU/edit?usp=sharing)

**Phase 1:**
FE Change:
- [x] Introduce Catalog Concept
  -   [x] #5687
  -   [x] Catalog Persistence implementation https://github.com/StarRocks/starrocks/issues/5796
  -   [x] SQL syntax support implementation for CREATE/DROP/SHOW Catalog #5762 https://github.com/StarRocks/starrocks/issues/5796
  -   [x] SQL syntax support implementation for SHOW DATABASES FROM <catalog>
  -   [x] ConnectContext and currentCatalog adaptation
  -   [x] #6240 
- [x] FE Catalog refactor
  - [x] Split
      - [x] Implement LocalMetaStore #6211 
      - [x] #5739
      - [x] #6234
      - [x] Splitting of other modules（TBD）
  - [x] Adaptation
      - [x] LocalMetaStore adaptation for FE
      - [x] GlobalStateMgr adaptation for FE #5739 
      - [x] NodeMgr adaptation for FE
      - [x] Adaptation of other modules（TBD）
- [x] Connector APIs
  - [x] #5738
  - [x] #5737
  - [x] HiveMetadata implementation https://github.com/StarRocks/starrocks/issues/5796
  - [x] HiveConnector implementation https://github.com/StarRocks/starrocks/issues/5796
  - [ ] MemoryConnector implementation
- [x] Abstraction of FE Core Engine
  - [x] #5776
  - [x] CatalogManager implementation
  - [x] #5671
  - [x] Manager adaption for FE
- [x] Module Compatibility and Adaptation
  - [x] Compatibility and Adaptation for Analyzer 
  - [x] Compatibility and Adaptation for Parser
  - [x] Compatibility and Adaptation Optimizer
- [ ] Hive metadata synchronization adaptation 
  - [x] Implementation and adaptation of HiveTable creation through HiveMetaCache
  - [x] Cache additions such as Table schema
  - [x] Manual refresh adaptation
  - [x] Auto-increment Hive metadata cache synchronization adaptation
    - [x] Support meta cache synchronization for Connector Table
    - [ ] Support for handling CreateTableEvent
    - [x] Supports the processing of AlterTableEvent, mainly to support the update of Schema Change
    - [x] Modification and adaptation of Merge rules for processing Events
- [ ] Catalog adaptation in terms of permissions
- [ ] Unit tests

BE Change:
- [x] #5763
- [x] Adaptation
  - [x] #5734
  - [x] #5742
  - [x] #5733
  - [x] #5735
- [ ] Unit tests
