### ISSUE TITLE
[Feature] bulk load optimization

### ISSUE THREAD

**Issue by luohaha** [StarRocks/starrocks#53954]
- [x] https://github.com/StarRocks/starrocks/pull/54285
- [x] https://github.com/StarRocks/starrocks/pull/53973
- [x] https://github.com/StarRocks/starrocks/pull/53921
- [x] https://github.com/StarRocks/starrocks/pull/54647

## Feature request

**Is your feature request related to a problem? Please describe.**

When performing large data ingestions, memory limitations during the ingestion process can result in the final Rowset containing a large number of segment files. This negatively impacts query performance and increases resource consumption (CPU and memory) during subsequent compaction operations.

**Describe the solution you'd like**

To address this, we propose a new large data ingestion strategy that spills data during the ingestion process and assembles it into final segment files in the final stage of the ingestion. This approach reduces the number of segment files in the Rowset.

![image](https://github.com/user-attachments/assets/db194490-d3d2-4c1e-945b-b5d259e609ca)

- [x] Part 1 - Block manager #53921 
- [x] Part 2 - Spill mem table sink #53973 
- [x] Part 3 - Block merger #54285

### Detailed design doc
https://docs.google.com/document/d/1GUW4S00xk5i_lnmNODNrybRqHds_6aitm6yY_1_KrWg/edit?usp=sharing

**Comment by luohaha** [comment]
https://github.com/StarRocks/starrocks/pull/54862
