### ISSUE TITLE
[Enhancement] Optimize the memory usage of rows between unbounded preceding and current row in window function

### ISSUE THREAD

**Issue by trueeyu** [StarRocks/starrocks#5829]
## Enhancement

Currently, if the partition in window function is relatively large, it will consume a lot of memory for Frame: ROWS BETWEEND UNBOUNDING PRECEDING AND CURRENT ROW, such as:

```
select lo_partkey, lo_custkey, lo_suppkey, lo_quantity, lo_discount, lo_shipmode, row_number() over(order by lo_partkey) as _num from lineorder
```

# Old Algorithms

![image](https://user-images.githubusercontent.com/11428742/167244452-7e6dbaea-0f93-4dc5-a10d-a688f8fc8d9d.png)

![image](https://user-images.githubusercontent.com/11428742/167244846-ee2261d2-9151-4625-afeb-2f1b934c7583.png)

STEP 1. Get all Chunks of the current Partition
STEP 2. Iterate over all Chunks of the current Partition and calculate the output result

for the example above

* PartitionColumn: not exist
* OrderByColumn: lo_partkey
* other output column: lo_partkey, lo_custkey, lo_suppkey, lo_quantity, lo_discount, lo_shipmode

Problems of old algorithm

If there is no PartitionColumn, then all the data belongs to a Partition, which needs to be cached in ChunkArray first. The theoretical memory consumption is: ChunkMem * Chunk quantity + OrderByColumn memory

# New Algorithm

The new algorithm only solves the problem that other outputs need to be cached in ChunkArray, and the memory optimization of  OrderByColumn and PartitionColumn will be done later

![image](https://user-images.githubusercontent.com/11428742/167244690-a94e5066-7cd5-4341-b736-2e1efa2ba2c2.png)

Get a Chunk and directly calculate the output, no need to cache all the chunk data of partition, If to the Partition boundary, Reset Partition State

# Task

- [x] add _found_partition_end to Analytor, which record the last found position, because we may have not found the partition end in current get next https://github.com/StarRocks/starrocks/pull/5831
- [x] refactor the code for later add optimize for rows between unbounded preceding and current row in window function https://github.com/StarRocks/starrocks/pull/5850
- [x] optimize the binary search of find first not equal value https://github.com/StarRocks/starrocks/pull/5864
- [x] add interface for reset next partition state https://github.com/StarRocks/starrocks/pull/5869
- [x] add optimize for rows between unbounded preceding and current row in window function in non-pipeline engine https://github.com/StarRocks/starrocks/pull/5883
- [ ] add optimize for rows between unbounded preceding and current row in window function in pipeline engine https://github.com/StarRocks/starrocks/pull/6036
