### ISSUE TITLE
[Phase 2]Introducing a new framework for StarRocks to connects to external data source more easily

### ISSUE THREAD

**Issue by stephen-shelby** [StarRocks/starrocks#7268]
This is an overview for phase 2 of #5062 , we can track all the issues and prs of connector(phase 2) here.
 - [ ] New Connectors
   - [ ] Iceberg(#6906 )
   - [ ] Hudi
   - [ ] [JDBC (MySQL or PostgreSQL)](https://github.com/StarRocks/starrocks/issues/7271)
   - [ ] [ElasticSearch](https://github.com/StarRocks/starrocks/issues/7272)
- [ ] FE change:
  - [ ] FE core engine abstraction
    - [ ] Table&Database abstraction
    - [ ] TableHandle Definition
    - [ ] FE optimizer support implementation
      - [ ] Manager implementation of optimizer pushdown
      - [ ] Refactoring of optimization rules related to data source(TBD)
    - [ ] FE ScanRange support implementation
      - [ ] ScanRangeManager implementation
  - [ ] FE Connector APIs
    - [x] #7446
    - [ ] Optimizer APIs
    - [ ] SPI module（TBD）
    - [ ] Move some code of core module into common module(For spi usage)
  - [ ] External ScanNode support and implementation
  - [ ] [Connector plugin mechanism](https://github.com/StarRocks/starrocks/issues/7279)
  - [ ] Refactor Hive Connector
  - [ ] Necessary statement
    - [ ] [Support `desc table` of external catalog](https://github.com/StarRocks/starrocks/issues/7285)
    - [ ] [Support `show create table` of external catalog](https://github.com/StarRocks/starrocks/issues/7286)
- [ ] FE&BE communication protocol implementation
  - [ ] Thrift

**Comment by stephen-shelby** [comment]
cc @DorianZheng @caneGuy

**Comment by RowenWoo** [comment]
pick elasticsearch-connector
